### ISSUE TITLE
[CHANGE] poprawić błedy ortograficzne w tekście - test

### ISSUE THREAD

**Issue by willazakopane** [Maciej85Lodz/willazakopane.pl#6]
**Is your change request related to a problem? Please describe.**
***Czy Twoja prośba o zmianę jest związana z problemem? Proszę opisz.***
 / No
 / Nie

**Describe the change you'd like**
***Opisz zmianę, którą chcesz nanieść na projekt***
***A clear and concise description of what you want to change.***
Is the change related to:
Main Information;
Main Foto;
Gallery;

***Jasny i zwięzły opis tego, co chcesz zmienić.***
***Czy zmiana dotyczy:***
Informacje Główne; 
Main Foto; 
Galeria; 
Rezerwacja - ceny; 
Inny;

**Describe the details of what should be changed**
A clear and concise description of the change you've considered.

**Opisz szczegóły tego, co powinno zostać zmienione.**
Jasny i zwięzły opis rozważanej zmiany.
poprawić błedy ortograficzne w tekście plus wymienić zdjecie główne i dodać zdjęcia w galerii

**Comment by Maciej85Lodz** [comment]
all done.
